Add "Set Recommended Brush Size" button
ulitiy/artworkout-figma pull request #16
Opened 2022-12-24 23:05 UTC by ant4x

2022-12-24 23:56 UTC, ulitiy requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/16)* status: all files reviewed, 5 unresolved discussions (waiting on @ant4x)

___
*[`src/app/components/DisplayForm.tsx` line 46 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/16#-NK5PaHI8vBkPxzBaPqQ:-NK5PaHI8vBkPxzBaPqR:bj71638) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/0c97d195fb7fb40de6c132977197f20bc2b7362e/src/app/components/DisplayForm.tsx#L46)):*
> ```XML
>       .then((bs) => setSuggestedBrushSize(bs))
>       .catch((err) => console.error(err))
>   }, [onListUpdate])
> ```

Бессмыслица, `onListUpdate` это функция, ты подписываешься на ее изменение. У тебя оно один раз выполняется и дальше не обновляется. Либо наоборот функция каждый раз переобъявляется и эффект тоже срабатывает при каждом рендере.

И прошу не использовать промисы, мы можем всё делает через async, не надо примешивать нам легаси в код. Посмотри как это делают авторы реакта:
https://github.com/facebook/react/issues/14326
___
*[`src/app/components/DisplayForm.tsx` line 77 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/16#-NK5YG233TM_Y5PFkAAM:-NK5YG2471XGSyOoVOIC:b-ed3c41) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/0c97d195fb7fb40de6c132977197f20bc2b7362e/src/app/components/DisplayForm.tsx#L77)):*
> ```XML
>         setStepCount(settings.stepCount)
>         setStepNumber(settings.stepNumber)
>         setDisplayMode(settings.displayMode)
> ```

Вот сюда же явно просится дописать. Да, это emit/on, от которых мы избавимся, но пока не избавились. Потом всё пачкой и перепишешь на RPC.
___
*[`src/app/components/DisplayForm.tsx` line 180 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/16#-NK5T2UV3_tqVDHgauky:-NK5T2UV3_tqVDHgaukz:b-76t94h) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/0c97d195fb7fb40de6c132977197f20bc2b7362e/src/app/components/DisplayForm.tsx#L180)):*
> ```XML
>                 value={template}
>                 onChange={(e) => {
>                   if (e.target.value === 'multistep-bg') {
> ```

убери логику в setTemplate, зачем она здесь?
___
*[`src/app/components/DisplayForm.tsx` line 211 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/16#-NK5TOnY2FKWJCOPntro:-NK5TOnY2FKWJCOPntrp:b-vbtj38) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/0c97d195fb7fb40de6c132977197f20bc2b7362e/src/app/components/DisplayForm.tsx#L211)):*
> ```XML
>               Brush size (AD)
>             </Form.Label>
>             <Col className='d-flex'>
> ```

просто создай еще одну колонку, проставь ширину на колонках, чтобы она не прыгала.
___
*[`src/plugin/tune-rpc.ts` line 83 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/16#-NK5W7lM11ST4lbJqg_u:-NK5W7lM11ST4lbJqg_v:b-9ie3on) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/0c97d195fb7fb40de6c132977197f20bc2b7362e/src/plugin/tune-rpc.ts#L83)):*
> ```XML
> 
> export function getBrushSize() {
>   const selection = figma.currentPage.selection
> ```

А если у тебя selection не совпадает с тем, что выбрано в плагине? Ты покажешь просто неверные данные.

Во-первых, это возможно (например, я выбрал input или другой внутренний элемент, тогда у меня выделение в плагине и в реакте не совпадает),
во-вторых, не надо надеяться, что кто-то другой не сломает то, на что ты необоснованно опирался.

В любом случае, это всё отсюда переезжает в emit


<!-- Sent from Reviewable.io -->

2022-12-25 19:45 UTC, ant4x reviewed
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/16)* status: 1 of 8 files reviewed, 5 unresolved discussions (waiting on @ulitiy)

___
*[`src/app/components/DisplayForm.tsx` line 46 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/16#-NK5PaHI8vBkPxzBaPqQ:-NK9UR108CuW9jIXi3kR:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/0c97d195fb7fb40de6c132977197f20bc2b7362e/src/app/components/DisplayForm.tsx#L46)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Бессмыслица, `onListUpdate` это функция, ты подписываешься на ее изменение. У тебя оно один раз выполняется и дальше не обновляется. Либо наоборот функция каждый раз переобъявляется и эффект тоже срабатывает при каждом рендере.

И прошу не использовать промисы, мы можем всё делает через async, не надо примешивать нам легаси в код. Посмотри как это делают авторы реакта:
https://github.com/facebook/react/issues/14326
</blockquote></details>

Done.
___
*[`src/app/components/DisplayForm.tsx` line 77 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/16#-NK5YG233TM_Y5PFkAAM:-NK9UTVZ-bE4NCX-pI8p:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/0c97d195fb7fb40de6c132977197f20bc2b7362e/src/app/components/DisplayForm.tsx#L77)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Вот сюда же явно просится дописать. Да, это emit/on, от которых мы избавимся, но пока не избавились. Потом всё пачкой и перепишешь на RPC.
</blockquote></details>

Done.
___
*[`src/app/components/DisplayForm.tsx` line 180 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/16#-NK5T2UV3_tqVDHgauky:-NK9UVZm2Z_IgE2Kuul6:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/0c97d195fb7fb40de6c132977197f20bc2b7362e/src/app/components/DisplayForm.tsx#L180)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

убери логику в setTemplate, зачем она здесь?
</blockquote></details>

Done.
___
*[`src/app/components/DisplayForm.tsx` line 211 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/16#-NK5TOnY2FKWJCOPntro:-NK9UWw57_ID8xvGzQWr:b-kaesqq) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/0c97d195fb7fb40de6c132977197f20bc2b7362e/src/app/components/DisplayForm.tsx#L211)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

просто создай еще одну колонку, проставь ширину на колонках, чтобы она не прыгала.
</blockquote></details>

Странно, у меня ничего не прыгало. Попробовал сделать иначе.
___
*[`src/plugin/tune-rpc.ts` line 83 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/16#-NK5W7lM11ST4lbJqg_u:-NK9Uo-cBCvLiofVRMTy:b-rk6nc7) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/0c97d195fb7fb40de6c132977197f20bc2b7362e/src/plugin/tune-rpc.ts#L83)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

А если у тебя selection не совпадает с тем, что выбрано в плагине? Ты покажешь просто неверные данные.

Во-первых, это возможно (например, я выбрал input или другой внутренний элемент, тогда у меня выделение в плагине и в реакте не совпадает),
во-вторых, не надо надеяться, что кто-то другой не сломает то, на что ты необоснованно опирался.

В любом случае, это всё отсюда переезжает в emit
</blockquote></details>

Переделал.


<!-- Sent from Reviewable.io -->

2022-12-25 19:58 UTC, ulitiy approved these changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ant4x)



<!-- Sent from Reviewable.io -->

2022-12-25 20:04 UTC, ulitiy requested changes
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/16)* status: all files reviewed, 1 unresolved discussion (waiting on @ant4x)

___
*[`src/app/components/DisplayForm.tsx` line 215 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/16#-NK9scbbDJ3m5XTEIjtx:-NK9scbc6QdDBEmvIrbk:b4202i8) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/a5e7925d072fb0de899901f5ef44306714c52f42/src/app/components/DisplayForm.tsx#L215)):*
> ```XML
>               />
>             </Col>
>             <Col xs={2} className='p-0 mx-1'>
> ```

убирай все эти костыли


<!-- Sent from Reviewable.io -->

2022-12-25 20:25 UTC, ant4x reviewed
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/16)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @ulitiy)

___
*[`src/app/components/DisplayForm.tsx` line 215 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/16#-NK9scbbDJ3m5XTEIjtx:-NK9wlYq64UDU6nSDvMX:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/a5e7925d072fb0de899901f5ef44306714c52f42/src/app/components/DisplayForm.tsx#L215)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

убирай все эти костыли
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-25 22:27 UTC, ulitiy approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ant4x)



<!-- Sent from Reviewable.io -->

2022-12-25 22:27 UTC, merged