Implement 'Import Texts' feature
ulitiy/artworkout-figma pull request #18
Opened 2023-01-09 20:20 UTC by ant4x

2023-01-09 21:07 UTC, ulitiy requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/18)* status: all files reviewed, 3 unresolved discussions (waiting on @ant4x)

___
*[`src/app/components/App.tsx` line 44 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLNHZEf10T5omAbK9OK:-NLNHZEf10T5omAbK9OL:bqwccm0) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8301a651c0df6c4d48e16ffa56a5bc8e39d1bd55/src/app/components/App.tsx#L44)):*
> ```XML
>   async function importTexts() {
>     let failed = false
>     const regexp = /^"([^"]+)" = "(.*)";\s*$/g
> ```

не понял, почему в начале `^"`?
___
*[`src/app/components/App.tsx` line 104 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLNHGFqAGHn3N_uUmC7:-NLNHGFqAGHn3N_uUmC8:b-4ps8lb) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8301a651c0df6c4d48e16ffa56a5bc8e39d1bd55/src/app/components/App.tsx#L104)):*
> ```XML
>       </Tab>
> 
>       <Tab eventKey='format' title='Format' className='m-2'>
> ```

Я думаю, пришло время выделить этот таб в отдельный компонент.
___
*[`src/plugin/format-rpc.ts` line 48 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLNLcZsEanp4eXkHM_U:-NLNLcZsEanp4eXkHM_V:ber1axw) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8301a651c0df6c4d48e16ffa56a5bc8e39d1bd55/src/plugin/format-rpc.ts#L48)):*
> ```XML
>   await figma.loadFontAsync({ family: 'Inter', style: 'Regular' })
>   const textNodes: TextNode[] = strings.map((string) => {
>     const text = figma.createText()
> ```

Не надо ничего создавать, надо заменять СООТВЕТСТВУЮЩИЕ строки.


<!-- Sent from Reviewable.io -->

2023-01-12 21:08 UTC, ant4x reviewed
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/18)* status: 2 of 14 files reviewed, 4 unresolved discussions (waiting on @ulitiy)

___
*[`tsconfig.json` line 5 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLbn1SB2hwfRrCWO9V8:-NLbn1SB2hwfRrCWO9V9:b-ojrlt) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e61624e2a7c47203af766cbbae425292a313e27c/tsconfig.json#L5)):*
> ```jsonc
>     "target": "es6",
>     "jsx": "react",
>     "lib": ["es6", "dom", "ES2021.String"],
> ```

Мне это потребовалось, чтобы использовать String.replaceAll() -- так нормально?
Если полностью поставить 'ES2021' вместо 'ES6' - вылазят ошибки компиляции в других местах и я не знаю, как их починить.
___
*[`src/app/components/App.tsx` line 44 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLNHZEf10T5omAbK9OK:-NLQSwOh8_8EmsuTx-AI:b-rmmovm) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8301a651c0df6c4d48e16ffa56a5bc8e39d1bd55/src/app/components/App.tsx#L44)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

не понял, почему в начале `^"`?
</blockquote></details>

Чтобы быть 100% уверенным, что regexp даст не более 1 совпадения на строку (мы матчим всю строку целиком).
___
*[`src/app/components/App.tsx` line 104 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLNHGFqAGHn3N_uUmC7:-NLQTF8a3wjdGoS7X7pO:b-67q6a2) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8301a651c0df6c4d48e16ffa56a5bc8e39d1bd55/src/app/components/App.tsx#L104)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Я думаю, пришло время выделить этот таб в отдельный компонент.
</blockquote></details>

Done. Я также, для аккуратности, выделил и CreateTab в отдельный компонент.
___
*[`src/plugin/format-rpc.ts` line 48 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLNLcZsEanp4eXkHM_U:-NLbm1nECAI-DojvcS5L:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8301a651c0df6c4d48e16ffa56a5bc8e39d1bd55/src/plugin/format-rpc.ts#L48)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Не надо ничего создавать, надо заменять СООТВЕТСТВУЮЩИЕ строки.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-13 20:46 UTC, ulitiy requested changes
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/18)* status: all files reviewed, 8 unresolved discussions (waiting on @ant4x)

___
*[`src/app/components/App.tsx` line 44 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLNHZEf10T5omAbK9OK:-NLgfOkT4rvAg0vqLok-:b-l0ztw) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8301a651c0df6c4d48e16ffa56a5bc8e39d1bd55/src/app/components/App.tsx#L44)):*
<details><summary><i>Previously, ant4x (Anthony Fox) wrote…</i></summary><blockquote>

Чтобы быть 100% уверенным, что regexp даст не более 1 совпадения на строку (мы матчим всю строку целиком).
</blockquote></details>

Да, туплю
___
*[`src/app/components/CreateTab.tsx` line 5 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLgs9pdD__cMJA_OQvz:-NLgs9pdD__cMJA_OQw-:ba71sl0) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e61624e2a7c47203af766cbbae425292a313e27c/src/app/components/CreateTab.tsx#L5)):*
> ```XML
> import { pluginApi } from '../../rpc-api'
> import { emit } from '../../events'
> import './CreateTab.css'
> ```

Смысла импортировать ТАК в нескольких местах нет, это же не css module, он у тебя всё равно будет работать глобально.
___
*[`src/app/components/FormatTab.css` line 1 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLgs51l2lARoSKDlAbJ:-NLgs51l2lARoSKDlAbK:b-jog23f) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e61624e2a7c47203af766cbbae425292a313e27c/src/app/components/FormatTab.css#L1)):*
> ```CSS
> .plugin-btn {
> ```

повторение кода
___
*[`src/app/components/FormatTab.tsx` line 35 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLggaFBC1xIHRPNmqX7:-NLggaFBC1xIHRPNmqX8:boje1fh) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e61624e2a7c47203af766cbbae425292a313e27c/src/app/components/FormatTab.tsx#L35)):*
> ```XML
>       .map((str) => str.trimEnd())
>       .filter((str) => str.length > 0)
>       .map((str) => {
> ```

foreach семантически осмысленнее наверно, map это всё-таки преобразование из одного массива в другой
___
*[`src/plugin/format-rpc.ts` line 35 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLghtW07O8yNu-wD4xi:-NLghtW07O8yNu-wD4xj:bj2pbnm) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e61624e2a7c47203af766cbbae425292a313e27c/src/plugin/format-rpc.ts#L35)):*
> ```XML
> }
> 
> function unescape(str: string) {
> ```

Это сложно читать и нет никакой необходимости в этом коде, для этого созданы регексы. Точно так же replaceall.
___
*[`src/plugin/format-rpc.ts` line 108 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLgnt4a45wlCRJOfFNv:-NLgnt4c-D1h-HOdU0_s:byntdw5) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e61624e2a7c47203af766cbbae425292a313e27c/src/plugin/format-rpc.ts#L108)):*
> ```XML
>   const texts = findTexts(figma.currentPage)
>   await figma.loadFontAsync({ family: 'Inter', style: 'Regular' })
>   await figma.loadFontAsync({ family: 'Montserrat', style: 'Regular' })
> ```

You can pass the font stored on an existing text node.

https://www.figma.com/plugin-docs/api/properties/figma-loadfontasync/

Почему ты хардкодишь здесь шрифты вместо того чтобы подгружать те, что по факту есть на ноде?
___
*[`src/plugin/format-rpc.ts` line 112 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLgoLIJ7YTyXc9Sfnnd:-NLgoLIJ7YTyXc9Sfnne:b-m7ukfi) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e61624e2a7c47203af766cbbae425292a313e27c/src/plugin/format-rpc.ts#L112)):*
> ```XML
>     const formattedText = getFormattedText(txt)
>     const translation: string = translations[formattedText]
>     if (translation !== undefined) {
> ```

early return
___
*[`src/plugin/format-rpc.ts` line 129 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLgq0MQ-QH1AylEDAJE:-NLgq0MQ-QH1AylEDAJF:b-csxuo0) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e61624e2a7c47203af766cbbae425292a313e27c/src/plugin/format-rpc.ts#L129)):*
> ```XML
>       // do not allow segments length mismatch
>       if (newSegments.length !== oldSegments.length) {
>         errorMessage = `Segment count mismatch: expected ${oldSegments.length}, got ${newSegments.length}`
> ```

Как юзер поймет, на какой строке ошибка?


<!-- Sent from Reviewable.io -->

2023-01-15 23:56 UTC, ant4x reviewed
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/18)* status: 5 of 14 files reviewed, 8 unresolved discussions (waiting on @ulitiy)

___
*[`src/app/components/CreateTab.tsx` line 5 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLgs9pdD__cMJA_OQvz:-NLrmPDMCmL_B649nufY:bk30spg) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e61624e2a7c47203af766cbbae425292a313e27c/src/app/components/CreateTab.tsx#L5)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Смысла импортировать ТАК в нескольких местах нет, это же не css module, он у тебя всё равно будет работать глобально.
</blockquote></details>

Исправил
___
*[`src/app/components/FormatTab.tsx` line 35 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLggaFBC1xIHRPNmqX7:-NLrqUxl82wCZivcKxf2:bk30spg) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e61624e2a7c47203af766cbbae425292a313e27c/src/app/components/FormatTab.tsx#L35)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

foreach семантически осмысленнее наверно, map это всё-таки преобразование из одного массива в другой
</blockquote></details>

Исправил
___
*[`src/plugin/format-rpc.ts` line 35 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLghtW07O8yNu-wD4xi:-NLrq_acAuw9_SecBivk:b-rk6ncl) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e61624e2a7c47203af766cbbae425292a313e27c/src/plugin/format-rpc.ts#L35)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Это сложно читать и нет никакой необходимости в этом коде, для этого созданы регексы. Точно так же replaceall.
</blockquote></details>

Переделал 
___
*[`src/plugin/format-rpc.ts` line 108 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLgnt4a45wlCRJOfFNv:-NLrqedE0Xz43VjIvZi2:bx4il2w) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e61624e2a7c47203af766cbbae425292a313e27c/src/plugin/format-rpc.ts#L108)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

You can pass the font stored on an existing text node.

https://www.figma.com/plugin-docs/api/properties/figma-loadfontasync/

Почему ты хардкодишь здесь шрифты вместо того чтобы подгружать те, что по факту есть на ноде?
</blockquote></details>

Хотел уточнить одинаковые ли мы используем шрифты. Доделал.
___
*[`src/plugin/format-rpc.ts` line 112 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLgoLIJ7YTyXc9Sfnnd:-NLrr1pp2W7eXExc5QAA:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e61624e2a7c47203af766cbbae425292a313e27c/src/plugin/format-rpc.ts#L112)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

early return
</blockquote></details>

Done.
___
*[`src/plugin/format-rpc.ts` line 129 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLgq0MQ-QH1AylEDAJE:-NLrr33L4ACW4QXQY4bq:bk30spg) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e61624e2a7c47203af766cbbae425292a313e27c/src/plugin/format-rpc.ts#L129)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Как юзер поймет, на какой строке ошибка?
</blockquote></details>

Исправил
___
*[`tsconfig.json` line 5 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLbn1SB2hwfRrCWO9V8:-NLrr5dj8D8_efDlw64M:b-c8mo9i) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e61624e2a7c47203af766cbbae425292a313e27c/tsconfig.json#L5)):*
<details><summary><i>Previously, ant4x (Anthony Fox) wrote…</i></summary><blockquote>

Мне это потребовалось, чтобы использовать String.replaceAll() -- так нормально?
Если полностью поставить 'ES2021' вместо 'ES6' - вылазят ошибки компиляции в других местах и я не знаю, как их починить.
</blockquote></details>

Переделал на replace c regexp, поэтому вернул как было
___
*[`src/app/components/FormatTab.css` line 1 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLgs51l2lARoSKDlAbJ:-NLrrCSj9HVSLIzVdOq5:b7dcr3s) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e61624e2a7c47203af766cbbae425292a313e27c/src/app/components/FormatTab.css#L1)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

повторение кода
</blockquote></details>

Убрал


<!-- Sent from Reviewable.io -->

2023-01-23 17:10 UTC, ulitiy requested changes
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/18)* status: all files reviewed, 2 unresolved discussions (waiting on @ant4x)

___
*[`src/app/components/CreateTab.tsx` line 5 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLgs9pdD__cMJA_OQvz:-NMUaX_g09x2SQQWu1F2:brlopm0) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e61624e2a7c47203af766cbbae425292a313e27c/src/app/components/CreateTab.tsx#L5)):*
<details><summary><i>Previously, ant4x (Anthony Fox) wrote…</i></summary><blockquote>

Исправил
</blockquote></details>

В любом случае, не надо импортировать в нескольких местах. Это не css module. Импортируй где-то в App тогда.


<!-- Sent from Reviewable.io -->

2023-01-23 17:18 UTC, ulitiy requested changes
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/18)* status: all files reviewed, 3 unresolved discussions (waiting on @ant4x)

___
*[`src/plugin/format-rpc.ts` line 92 at r3](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NMUcBKG0cOSP_qSOFrC:-NMUcBKH70xYPZbKnipc:b-fsc5i2) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d87d67ee7f7434b6c710f963ce1a8dd79ab6f7ea/src/plugin/format-rpc.ts#L92)):*
> ```XML
>       )
>   )
>   for (let font of uniqueFonts) {
> ```

старайся не использовать for вместо foreach. Да, for быстрее. Просто как конвенция.


<!-- Sent from Reviewable.io -->

2023-01-23 17:20 UTC, ulitiy approved these changes
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/18)* status: all files reviewed, 2 unresolved discussions (waiting on @ant4x)



<!-- Sent from Reviewable.io -->

2023-01-23 17:37 UTC, ant4x reviewed
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/18)* status: all files reviewed, 1 unresolved discussion (waiting on @ulitiy)

___
*[`src/app/components/CreateTab.tsx` line 5 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NLgs9pdD__cMJA_OQvz:-NMUcR061VOVcbk5UZz5:bulfynq) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e61624e2a7c47203af766cbbae425292a313e27c/src/app/components/CreateTab.tsx#L5)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

В любом случае, не надо импортировать в нескольких местах. Это не css module. Импортируй где-то в App тогда.
</blockquote></details>

У меня видимо неверное представление о импорте CSS, почитаю. Изменил.
___
*[`src/plugin/format-rpc.ts` line 92 at r3](https://reviewable.io/reviews/ulitiy/artworkout-figma/18#-NMUcBKG0cOSP_qSOFrC:-NMUdSKH4vFFt5RehBJg:b-3f6qty) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d87d67ee7f7434b6c710f963ce1a8dd79ab6f7ea/src/plugin/format-rpc.ts#L92)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

старайся не использовать for вместо foreach. Да, for быстрее. Просто как конвенция.
</blockquote></details>

Если делать forEach, TS ругается на await, пишет - 'await' expressions are only allowed within async functions and at the top levels of modules.


<!-- Sent from Reviewable.io -->

2023-01-23 17:48 UTC, ulitiy approved these changes
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/18)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ant4x)



<!-- Sent from Reviewable.io -->

2023-01-28 21:10 UTC, merged