New lesson lint fix
ulitiy/artworkout-figma pull request #20
Opened 2023-01-31 13:08 UTC by Ivan-okolzin

2023-02-02 03:30 UTC, ulitiy requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/20)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Ivan-okolzin)

___
*[`src/plugin/linter.ts` line 92 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/20#-NNF7t8rAfoB6Jd9VxiT:-NNF7t8rAfoB6Jd9VxiU:b1q4lzf) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/620d3cc58697b04aca0e350e5d03f531eb5aa927/src/plugin/linter.ts#L92)):*
> ```XML
>       assert(f.opacity == 1, 'Image fill must not be opaque', page, node)
>     }
>     if (f.type === 'GRADIENT_LINEAR'){
> ```

Зачем эти требования нужны? Нужно исправить, чтобы прога воспринимала нормально черный и белый, а не пытаться всех заставить отказаться от этих цветов.

Для градиентов точно эти правила не нужны, т.к. task.js не умеет вынимать цвет кисти из градиента.

Отказ от белого/черного связан исключительно с тем, что фигма при экспорте их выгружает в white/black вместо ffffff/000000, что ломает task.js.
Цвет захватывается только с нод, имеющих тег rgb-template (https://trello.com/c/twDy4jQu/46 , отдельным ПР)

Для референса скинул в чат и закрепил task.js
___
*[`src/plugin/linter.ts` line 121 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/20#-NNF94_o4F0wP3CZ6LlF:-NNF94_o4F0wP3CZ6LlG:b9p207c) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/620d3cc58697b04aca0e350e5d03f531eb5aa927/src/plugin/linter.ts#L121)):*
> ```XML
>     assert(!rgbt, 'Stroke must be solid', page, node)
>     if (s.type === 'IMAGE'){
>       assert(s.opacity == 1, 'Image stroke must not be opaque', page, node)
> ```

Must be opaque наверно?


<!-- Sent from Reviewable.io -->

2023-02-02 03:30 UTC, ulitiy reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/20)* status: all files reviewed, 2 unresolved discussions (waiting on @Ivan-okolzin)



<!-- Sent from Reviewable.io -->

2023-02-02 09:38 UTC, Ivan-okolzin commented
Убрал правила для градиента, чтобы литер просто не падал (раз нет никаких правил пока для них), поправил надпись.

2023-02-03 04:47 UTC, ulitiy requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/20)* status: all files reviewed, 2 unresolved discussions (waiting on @Ivan-okolzin)

___
*[`-- commits` line 8 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/20#-NNKXKz81byJIbT8Y46Y):*
Не пиши коммиты по-русски. Давай попробуем `rebase -i` заодно, как себя поведет reviewable.
___
*[`src/plugin/linter.ts` line 109 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/20#-NNKYE44-jtxt6rOAD9B:-NNKYE44-jtxt6rOAD9C:b-6hq4wd) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8afbf7bc45b6d386c7f8f29b7c8e149e9fcc7753/src/plugin/linter.ts#L109)):*
> ```XML
> }
> 
> function lintStrokes(node: VectorNode, page: PageNode, strokes: Paint[], rgbt: string) {
> ```

Предлагаю вычислять rgbt внутри. В параметрах функции это избыточная инфа, тем более как string.
Пусть каждая функция будет более независима.
Пускай вычисляется 3 раза, нечего экономить циклы здесь.

Заодно можно добавить util функцию hasTag c регексом


<!-- Sent from Reviewable.io -->

2023-02-03 04:58 UTC, ulitiy requested changes
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/20)* status: all files reviewed, 2 unresolved discussions (waiting on @Ivan-okolzin)

___
*[`src/plugin/linter.ts` line 109 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/20#-NNKYE44-jtxt6rOAD9B:-NNKcj6o0qsvZp2qEiP9:bzhtxpr) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8afbf7bc45b6d386c7f8f29b7c8e149e9fcc7753/src/plugin/linter.ts#L109)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Предлагаю вычислять rgbt внутри. В параметрах функции это избыточная инфа, тем более как string.
Пусть каждая функция будет более независима.
Пускай вычисляется 3 раза, нечего экономить циклы здесь.

Заодно можно добавить util функцию hasTag c регексом
</blockquote></details>

Либо `getTags(n).includes('rgb-template')`


<!-- Sent from Reviewable.io -->

2023-02-03 13:58 UTC, Ivan-okolzin reviewed
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/20)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @ulitiy)

___
*[`-- commits` line 8 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/20#-NNKXKz81byJIbT8Y46Y):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Не пиши коммиты по-русски. Давай попробуем `rebase -i` заодно, как себя поведет reviewable.
</blockquote></details>

Done.
___
*[`src/plugin/linter.ts` line 109 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/20#-NNKYE44-jtxt6rOAD9B:-NNMZ65WE8OY5DTLxRQy:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8afbf7bc45b6d386c7f8f29b7c8e149e9fcc7753/src/plugin/linter.ts#L109)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Либо `getTags(n).includes('rgb-template')`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-05 21:35 UTC, ulitiy approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ivan-okolzin)



<!-- Sent from Reviewable.io -->

2023-02-06 19:14 UTC, ulitiy approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ivan-okolzin)



<!-- Sent from Reviewable.io -->

2023-02-06 19:14 UTC, merged