Set step order
ulitiy/artworkout-figma pull request #21
Opened 2023-02-02 22:09 UTC by ant4x

2023-02-05 21:17 UTC, ulitiy requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/21)* status: all files reviewed, 2 unresolved discussions (waiting on @ant4x)

___
*[`src/plugin/tune-rpc.ts` line 66 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/21#-NNSAyLy4bRm_erg0WBR:-NNSAyLz0YF-blmyS68c:b-phnoz0) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/5a572be55a27b5a8e49615c86b40ff28cdb731c2/src/plugin/tune-rpc.ts#L66)):*
> ```XML
> }
> 
> export function setStepOrder(steps: Step[], lastStepNumber: number = 1) {
> ```

Почему lastStepNumber задается снаружи? Почему его вычисление не убрать внутрь? На мой взгляд, этот параметр лишний и совершенно неожиданный для того, кто будет пользоваться этой функцией после тебя.

Рассуждения:
Я понимаю, если бы параметр назывался startWith, например. Плюс в JS нет именованных аргументов, т.е. в месте вызова ты должен знать сигнатуру метода (некоторые IDE ее подсвечивают, конечно, но это костыль, а обычно такое делается через объект options: { startWith }, чтобы читаемость была в любом редакторе.

Я бы не заморачивался с новыми шагами, я бы просто сделал один метод без параметров "сделать хорошо", который сам знает, что такое хорошо. Выбор в пользу архитектуры и читаемости, а не производительности.
___
*[`src/plugin/tune-rpc.ts` line 66 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/21#-NNYQnejE4iNJn-iI8ss:-NNYQnejE4iNJn-iI8st:b-9xvpy4) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/5a572be55a27b5a8e49615c86b40ff28cdb731c2/src/plugin/tune-rpc.ts#L66)):*
> ```XML
> }
> 
> export function setStepOrder(steps: Step[], lastStepNumber: number = 1) {
> ```

setStep`s`Order

и во всех местах тоже заменить Number на Order, раз уж у нас используется тег O - order, для консистентности.


<!-- Sent from Reviewable.io -->

2023-02-14 22:15 UTC, ant4x reviewed
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/21)* status: 0 of 1 approvals obtained, 0 of 12 files reviewed, 2 unresolved discussions (waiting on @ulitiy)

___
*[`src/plugin/tune-rpc.ts` line 66 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/21#-NNSAyLy4bRm_erg0WBR:-NOGjmXmDR3Rq0zNS_ZK:b-75v0b3) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/5a572be55a27b5a8e49615c86b40ff28cdb731c2/src/plugin/tune-rpc.ts#L66)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Почему lastStepNumber задается снаружи? Почему его вычисление не убрать внутрь? На мой взгляд, этот параметр лишний и совершенно неожиданный для того, кто будет пользоваться этой функцией после тебя.

Рассуждения:
Я понимаю, если бы параметр назывался startWith, например. Плюс в JS нет именованных аргументов, т.е. в месте вызова ты должен знать сигнатуру метода (некоторые IDE ее подсвечивают, конечно, но это костыль, а обычно такое делается через объект options: { startWith }, чтобы читаемость была в любом редакторе.

Я бы не заморачивался с новыми шагами, я бы просто сделал один метод без параметров "сделать хорошо", который сам знает, что такое хорошо. Выбор в пользу архитектуры и читаемости, а не производительности.
</blockquote></details>

Пересмотрел данную функцию и решил, что мне изначально не стоило менять твою, лучше создать новую, т.к. они преследуют разные цели. Переделал с учетом пожеланий. 
___
*[`src/plugin/tune-rpc.ts` line 66 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/21#-NNYQnejE4iNJn-iI8ss:-NOGkFo08cJf-XVl8Ji9:buvzq8c) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/5a572be55a27b5a8e49615c86b40ff28cdb731c2/src/plugin/tune-rpc.ts#L66)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

setStep`s`Order

и во всех местах тоже заменить Number на Order, раз уж у нас используется тег O - order, для консистентности.
</blockquote></details>

Поменял везде **number** на **order** (хотя, по моему мнению, не везде выглядит удачно). Например, в `DisplayForm.tsx` state setter `setStepOrder` теперь имеет то же название, что и функция. Как лучше поступить? Или ты имел в виду поменять только на моих (новых) функциях?


<!-- Sent from Reviewable.io -->

2023-02-14 22:31 UTC, ulitiy requested changes
> Reviewed 11 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/21)* status: 0 of 1 approvals obtained, 11 of 12 files reviewed, 5 unresolved discussions (waiting on @ant4x)

___
*[`src/app/components/CreateTab.tsx` line 9 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/21#-NOH-sTdA5vlhHpDcghF:-NOH-sTdA5vlhHpDcghG:b76fwjd) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/358bb94f44d4f16ce67887ab247dfc1c07358349/src/app/components/CreateTab.tsx#L9)):*
> ```XML
>   async function handleSplitByColor() {
>     await pluginApi.splitByColor()
>     emit('updateDisplay', { displayMode: 'all', stepOrder: 1 })
> ```

Здесь не надо, конечно.
___
*[`src/app/components/DisplayForm.tsx` line 17 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/21#-NOH0blt61ULmvx3_gdQ:-NOH0blt61ULmvx3_gdR:bt8x8gw) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/358bb94f44d4f16ce67887ab247dfc1c07358349/src/app/components/DisplayForm.tsx#L17)):*
> ```XML
>   const [displayMode, setDisplayMode] = useState('all')
>   const [template, setTemplate] = useState('')
>   const [stepOrder, setStepOrder] = useState(1)
> ```

Этот файл откати
___
*[`src/plugin/linter.ts` line 488 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/21#-NOH1CST3Pe1i95aSMf5:-NOH1CST3Pe1i95aSMf6:b742t9v) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/358bb94f44d4f16ce67887ab247dfc1c07358349/src/plugin/linter.ts#L488)):*
> ```XML
>   }
> 
>   updateDisplay(page, { displayMode: 'all', stepOrder: 1 })
> ```

Верни
___
*[`src/plugin/tune.ts` line 5 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/21#-NOH1Upx59ZN_Lre8Dws:-NOH1Upx59ZN_Lre8Dwt:b-cr1xhf) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/358bb94f44d4f16ce67887ab247dfc1c07358349/src/plugin/tune.ts#L5)):*
> ```XML
>   findLeafNodes,
>   getCurrentLesson,
>   getStepOrder,
> ```

Файл откати
___
*[`src/plugin/tune-rpc.ts` line 66 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/21#-NNYQnejE4iNJn-iI8ss:-NOH-ZssCLt3t9oe1HHM:b-lxl76f) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/5a572be55a27b5a8e49615c86b40ff28cdb731c2/src/plugin/tune-rpc.ts#L66)):*
<details><summary><i>Previously, ant4x (Anthony Fox) wrote…</i></summary><blockquote>

Поменял везде **number** на **order** (хотя, по моему мнению, не везде выглядит удачно). Например, в `DisplayForm.tsx` state setter `setStepOrder` теперь имеет то же название, что и функция. Как лучше поступить? Или ты имел в виду поменять только на моих (новых) функциях?
</blockquote></details>

на твоих, конечно.


<!-- Sent from Reviewable.io -->

2023-02-14 23:49 UTC, ant4x reviewed
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/21)* status: 0 of 1 approvals obtained, 4 of 12 files reviewed, 5 unresolved discussions (waiting on @ulitiy)

___
*[`src/plugin/tune.ts` line 5 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/21#-NOH1Upx59ZN_Lre8Dws:-NOHACEd8-ht_hEro9XZ:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/358bb94f44d4f16ce67887ab247dfc1c07358349/src/plugin/tune.ts#L5)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Файл откати
</blockquote></details>

Done.
___
*[`src/plugin/tune-rpc.ts` line 66 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/21#-NNYQnejE4iNJn-iI8ss:-NOHADsLBmQtJWBRnrUV:b-tsctfi) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/5a572be55a27b5a8e49615c86b40ff28cdb731c2/src/plugin/tune-rpc.ts#L66)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

на твоих, конечно.
</blockquote></details>

Отменил изменения
___
*[`src/app/components/CreateTab.tsx` line 9 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/21#-NOH-sTdA5vlhHpDcghF:-NOHA6-rDDWeX9IL-kej:b-e07ltm) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/358bb94f44d4f16ce67887ab247dfc1c07358349/src/app/components/CreateTab.tsx#L9)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Здесь не надо, конечно.
</blockquote></details>

Откатил
___
*[`src/app/components/DisplayForm.tsx` line 17 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/21#-NOH0blt61ULmvx3_gdQ:-NOHA8Ok6XXoTc914eqQ:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/358bb94f44d4f16ce67887ab247dfc1c07358349/src/app/components/DisplayForm.tsx#L17)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Этот файл откати
</blockquote></details>

Done.
___
*[`src/plugin/linter.ts` line 488 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/21#-NOH1CST3Pe1i95aSMf5:-NOHABMW6Q8LhxvjPrbL:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/358bb94f44d4f16ce67887ab247dfc1c07358349/src/plugin/linter.ts#L488)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Верни
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-15 03:32 UTC, ulitiy requested changes
> Reviewed 1 of 12 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/21)* status: 0 of 1 approvals obtained, all files reviewed, 2 unresolved discussions (waiting on @ant4x)

___
*[`src/plugin/tune-rpc.ts` line 79 at r3](https://reviewable.io/reviews/ulitiy/artworkout-figma/21#-NOI6LZzAyBR8NvNJATs:-NOI6LZzAyBR8NvNJATt:b-34m1ap) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/5f113c7ee41ee70edbd9579f2380ec990b9c4048/src/plugin/tune-rpc.ts#L79)):*
> ```XML
> export function tagUnorderedSteps() {
>   let startWith = getLastStepOrder()
>   if (startWith < 1) {
> ```

Тернарник, либо вообще убрать 0 внутрь функции выше, если это ничего не ломает
___
*[`src/plugin/tune-rpc.ts` line 83 at r3](https://reviewable.io/reviews/ulitiy/artworkout-figma/21#-NOI7JC6BTBbT26c8tvz:-NOI7JC6BTBbT26c8tw-:bdumrmc) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/5f113c7ee41ee70edbd9579f2380ec990b9c4048/src/plugin/tune-rpc.ts#L83)):*
> ```XML
>   }
>   const lesson = getCurrentLesson()
>   getSteps()
> ```

stepsByOrder(lesson) здесь устраняет необходимость в findOne


<!-- Sent from Reviewable.io -->

2023-02-16 18:56 UTC, ant4x reviewed
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/21)* status: 0 of 1 approvals obtained, 7 of 12 files reviewed, 2 unresolved discussions (waiting on @ulitiy)

___
*[`src/plugin/tune-rpc.ts` line 79 at r3](https://reviewable.io/reviews/ulitiy/artworkout-figma/21#-NOI6LZzAyBR8NvNJATs:-NOQZcXoDNGcAQ_hoaHp:b-gobrty) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/5f113c7ee41ee70edbd9579f2380ec990b9c4048/src/plugin/tune-rpc.ts#L79)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Тернарник, либо вообще убрать 0 внутрь функции выше, если это ничего не ломает
</blockquote></details>

Исправил.
___
*[`src/plugin/tune-rpc.ts` line 83 at r3](https://reviewable.io/reviews/ulitiy/artworkout-figma/21#-NOI7JC6BTBbT26c8tvz:-NOQZiJEDQI1HWqoeBRZ:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/5f113c7ee41ee70edbd9579f2380ec990b9c4048/src/plugin/tune-rpc.ts#L83)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

stepsByOrder(lesson) здесь устраняет необходимость в findOne
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-17 02:34 UTC, ulitiy approved these changes
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/21)* status: :shipit: complete! 1 of 1 approvals obtained, all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-02-17 23:58 UTC, merged