Show only rgb-template in previous mode
ulitiy/artworkout-figma pull request #24
Opened 2023-02-23 10:10 UTC by Ivan-okolzin

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ulitiy/artworkout-figma/24)

2023-02-24 00:39 UTC, ulitiy requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/24)* status: 0 of 1 approvals obtained, all files reviewed, 2 unresolved discussions (waiting on @Ivan-okolzin)

___
*[`src/plugin/tune.ts` line 179 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/24#-NP-pBP3AtigWy70lrR7:-NP-pBP4D0qCtNyaRqj7:bapdjw) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/24842e663e0fae277021647199769f4efdb07ea5/src/plugin/tune.ts#L179)):*
> ```XML
>     case 'all':
>       lesson.children.forEach((step) => {
>         step.visible = true
> ```

Ну тогда уже просто descendants возьми и убери лишнюю строку кода. Во всех трех случаях.
Хотя мне не нравится как Антон назвал эти функции...
___
*[`src/plugin/tune.ts` line 206 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/24#-NP-ptALDlWZGUpVO8HN:-NP-ptALDlWZGUpVO8HO:b-uyatjr) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/24842e663e0fae277021647199769f4efdb07ea5/src/plugin/tune.ts#L206)):*
> ```XML
>       })
>       descendantsWithoutSelf(step as GroupNode).forEach((v) => {
>         if (/RECTANGLE|ELLIPSE|VECTOR|TEXT/.test(v.type) && !getTags(v).includes('rgb-template')) {
> ```

Это некорректное условие. rgb-template может стоять на группе, например. Т.е. ты скроешь все элементы внутри группы rgb-template.

Тут, видимо, придется писать свою функцию, которая проходит вглубину и скрывает все листья дерева, но когда встречает rgb-template скипает элемент и всё поддерево и идёт дальше.

Альтернативно можно скрыть все листья сначала.
Потом найти все элементы rgb-template и показать их листья. Попроще код будет, но не знаю, будет ли тормозить.


<!-- Sent from Reviewable.io -->

2023-02-24 06:03 UTC, Ivan-okolzin commented
*[`src/plugin/tune.ts` line 179 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/24#-NP-pBP3AtigWy70lrR7:-NP108y-6YSka8rNSzOr:b-i73iog) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/24842e663e0fae277021647199769f4efdb07ea5/src/plugin/tune.ts#L179)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Ну тогда уже просто descendants возьми и убери лишнюю строку кода. Во всех трех случаях.
Хотя мне не нравится как Антон назвал эти функции...
</blockquote></details>

А в чем тогда вообще смысл заводить под это отдельную функцию, если можно просто обрезать родительскую ноду?


<!-- Sent from Reviewable.io -->

2023-02-24 12:48 UTC, Ivan-okolzin reviewed
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/24)* status: 0 of 1 approvals obtained, 1 of 6 files reviewed, 2 unresolved discussions (waiting on @ulitiy)

___
*[`src/plugin/tune.ts` line 206 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/24#-NP-ptALDlWZGUpVO8HN:-NP2SyGC5V72RhpHwxnI:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/24842e663e0fae277021647199769f4efdb07ea5/src/plugin/tune.ts#L206)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Это некорректное условие. rgb-template может стоять на группе, например. Т.е. ты скроешь все элементы внутри группы rgb-template.

Тут, видимо, придется писать свою функцию, которая проходит вглубину и скрывает все листья дерева, но когда встречает rgb-template скипает элемент и всё поддерево и идёт дальше.

Альтернативно можно скрыть все листья сначала.
Потом найти все элементы rgb-template и показать их листья. Попроще код будет, но не знаю, будет ли тормозить.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-24 16:10 UTC, ulitiy requested changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/24)* status: 0 of 1 approvals obtained, all files reviewed, 4 unresolved discussions (waiting on @Ivan-okolzin)

___
*[`src/plugin/tune.ts` line 179 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/24#-NP-pBP3AtigWy70lrR7:-NP39WU23gUWaw8rcU4h:bccn07q) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/24842e663e0fae277021647199769f4efdb07ea5/src/plugin/tune.ts#L179)):*
<details><summary><i>Previously, Ivan-okolzin wrote…</i></summary><blockquote>

А в чем тогда вообще смысл заводить под это отдельную функцию, если можно просто обрезать родительскую ноду?
</blockquote></details>

Лучше наоборот тогда, добавить. Descendants это всё-таки про потомков, ты не являешься своим собственным потомком)
___
*[`src/plugin/tune.ts` line 126 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/24#-NP3AKUR686xjJddLuhG:-NP3AKUR686xjJddLuhH:b-py8t6b) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/5b90285784f59ab4b9cb550baaa96ff7775f20e8/src/plugin/tune.ts#L126)):*
> ```XML
> }
> 
> function showOnlyRGBTemplate(group: GroupNode) {
> ```

group->node
___
*[`src/plugin/tune.ts` line 131 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/24#-NP3AMTeEJmhEvh4IlHO:-NP3AMTeEJmhEvh4IlHP:bkmrn9j) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/5b90285784f59ab4b9cb550baaa96ff7775f20e8/src/plugin/tune.ts#L131)):*
> ```XML
>       return
>     }
>     if (getTags(group).includes('rgb-template') || (/GROUP|BOOLEAN_OPERATION/.test(group.type) && !group.children)) {
> ```

Пустых групп не бывает же?
___
*[`src/plugin/tune.ts` line 135 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/24#-NP3AWU-3X-bTpgZNhiR:-NP3AWU-3X-bTpgZNhiS:b-m36r89) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/5b90285784f59ab4b9cb550baaa96ff7775f20e8/src/plugin/tune.ts#L135)):*
> ```XML
>     }
>     group.children.forEach((v) => {
>       if (/GROUP|BOOLEAN_OPERATION/.test(v.type) && group.children) {
> ```

аналогично, пустых групп не бывает?


<!-- Sent from Reviewable.io -->

2023-02-27 10:18 UTC, Ivan-okolzin reviewed
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/24)* status: 0 of 1 approvals obtained, 0 of 6 files reviewed, 4 unresolved discussions (waiting on @ulitiy)

___
*[`src/plugin/tune.ts` line 179 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/24#-NP-pBP3AtigWy70lrR7:-NPHNLVf5H8aBBvHMYhE:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/24842e663e0fae277021647199769f4efdb07ea5/src/plugin/tune.ts#L179)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Лучше наоборот тогда, добавить. Descendants это всё-таки про потомков, ты не являешься своим собственным потомком)
</blockquote></details>

Done.
___
*[`src/plugin/tune.ts` line 126 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/24#-NP3AKUR686xjJddLuhG:-NPHNIfG-0_60Y0l4NDu:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/5b90285784f59ab4b9cb550baaa96ff7775f20e8/src/plugin/tune.ts#L126)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

group->node
</blockquote></details>

Done.
___
*[`src/plugin/tune.ts` line 131 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/24#-NP3AMTeEJmhEvh4IlHO:-NPHNJ3Q1P7pHb6cvU3_:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/5b90285784f59ab4b9cb550baaa96ff7775f20e8/src/plugin/tune.ts#L131)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Пустых групп не бывает же?
</blockquote></details>

Done.
___
*[`src/plugin/tune.ts` line 135 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/24#-NP3AWU-3X-bTpgZNhiR:-NPHNJUr3vl2d5kVFFnd:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/5b90285784f59ab4b9cb550baaa96ff7775f20e8/src/plugin/tune.ts#L135)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

аналогично, пустых групп не бывает?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-28 03:35 UTC, ulitiy requested changes
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/24)* status: 0 of 1 approvals obtained, all files reviewed, 1 unresolved discussion (waiting on @Ivan-okolzin)

___
*[`src/plugin/util.ts` line 95 at r3](https://reviewable.io/reviews/ulitiy/artworkout-figma/24#-NPL4er6DUO_DF7ln3oo:-NPL4er6DUO_DF7ln3op:b2dz1i3) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d49e84a71925b6188993f60a23bafd626898a188/src/plugin/util.ts#L95)):*
> ```XML
> }
> 
> export function descendantsWithoutSelf(node: GroupNode): SceneNode[] {
> ```

просто descendants


<!-- Sent from Reviewable.io -->

2023-03-03 09:36 UTC, Ivan-okolzin reviewed
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/24)* status: 0 of 1 approvals obtained, 0 of 6 files reviewed, 1 unresolved discussion (waiting on @ulitiy)

___
*[`src/plugin/util.ts` line 95 at r3](https://reviewable.io/reviews/ulitiy/artworkout-figma/24#-NPL4er6DUO_DF7ln3oo:-NPaH3DABAdoBTiYkOE1:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d49e84a71925b6188993f60a23bafd626898a188/src/plugin/util.ts#L95)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

просто descendants
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-03 14:42 UTC, ulitiy approved these changes
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/24)* status: :shipit: complete! 1 of 1 approvals obtained, all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-03-03 14:43 UTC, merged