Animation changes
ulitiy/artworkout-figma pull request #32
Opened 2023-03-27 11:44 UTC by Ivan-okolzin

2023-03-28 04:52 UTC, ulitiy requested changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/32)* status: 0 of 1 approvals obtained, all files reviewed, 11 unresolved discussions (waiting on @Ivan-okolzin)

___
*[`src/app/components/DisplayForm.tsx` line 32 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaOUJUEWzVqHwNFHHb:-NRaOUJUEWzVqHwNFHHc:b-k7hzo3) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/app/components/DisplayForm.tsx#L32)):*
> ```XML
> 
> 
> export function DisplayForm() {
> ```

Предлагаю переименовать в TuneForm, и файл тоже. Только аккуратно, чтобы дифф не поехал
___
*[`src/app/components/DisplayForm.tsx` line 192 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaVT-L2RgOre9sROlT:-NRaVT-L2RgOre9sROlU:byo2est) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/app/components/DisplayForm.tsx#L192)):*
> ```XML
> 
>   useEffect(() => {
>     const unsubscribe = subscribe(rpcStore, () => {
> ```

Я предлагаю отказываться от отдельного локального useState и использовать valtio useSnapshot.
Зачем это дублирование стейта?
___
*[`src/app/components/uiRPC.ts` line 7 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaTG3K6GvgtK5UaZaK:-NRaTG3K6GvgtK5UaZaL:b-f42cb0) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/app/components/uiRPC.ts#L7)):*
> ```XML
> }
> 
> export async function updateProps(settings: {
> ```

Интерфейс можно вынести, чтобы не дублировать. И можно ли в таком случае этот файл влить в rpc-api? Мне не нравится название этого файла, я не понимаю из него, это UI вызывает RPC или это UI RPC API.
___
*[`src/app/models/rpc.ts` line 3 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaO4FzBMjH0hIF67Ze:-NRaO4FzBMjH0hIF67Zf:bhx05xx) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/app/models/rpc.ts#L3)):*
> ```XML
> import { proxy } from 'valtio'
> 
> export const rpcStore = proxy({
> ```

Нужно более точное название, TuneFormStore. И файл тоже. Вроде нет необходимости привязывать этот стор именно к RPC, лучше его привязать к потребителю, т.е. к форме.
___
*[`src/app/models/rpc.ts` line 4 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaYJZf62na16XD7RGZ:-NRaYJZf62na16XD7RG_:b-66s1zm) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/app/models/rpc.ts#L4)):*
> ```XML
> 
> export const rpcStore = proxy({
>   animationTag: undefined,
> ```

Если все эти свойства убрать в дополнительный объект, то заменять его можно будет одной строчкой, а не каждое свойство в отдельности.

Предлагаю назвать, например formProps или formProperties, как больше нравится, главное, чтобы совпадало с методами.
___
*[`src/app/models/rpc.ts` line 23 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaTPrREwAQgxeTAHo4:-NRaTPrREwAQgxeTAHo5:baoirn) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/app/models/rpc.ts#L23)):*
> ```XML
>     rpcStore.repeat = repeat
>   },
>   async updateProps(settings: {
> ```

интерфейс можно вынести, чтобы не дублировать.
___
*[`src/plugin/tune.ts` line 243 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaPZti3QxQOeGW7ZjC:-NRaPZtjEFIqHH_JXtDR:br60n1l) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/plugin/tune.ts#L243)):*
> ```XML
>     let selectionTags = getTags(figma.currentPage.selection[0])
>     selectionTags = selectionTags.filter((t) => !t.startsWith('wiggle') && !t.startsWith('fly-from-') && !t.startsWith('appear') && !t.startsWith('blink') && !t.startsWith('draw-line'))
>     selectionTags = selectionTags.filter((t) => !/d\d+/.test(t) && !/r\d+/.test(t) && !/r-\d+/.test(t) && !/d-\d+/.test(t))
> ```

сделай пожалуйста просто один .filter, без переопределения.

И одним регексом. Ты мэтчишь все анимации и в начале ставишь одно отрицание.
___
*[`src/plugin/tune.ts` line 314 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaXZVJE8_JJDN2s479:-NRaXZVJE8_JJDN2s47A:b-tnkuxr) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/plugin/tune.ts#L314)):*
> ```XML
> 
> export function updateDisplayFromForm(settings) {
>   updateDisplay(figma.currentPage, settings)
> ```

page сделать вторым опциональным параметром, от обёртки избавиться
___
*[`src/plugin/tune.ts` line 317 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaPI0c6d5MDo38K66m:-NRaPI0c6d5MDo38K66n:b-vsd62f) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/plugin/tune.ts#L317)):*
> ```XML
> }
> 
> export function updatePropsFromForm(settings) {
> ```

избыточная обёртка.
___
*[`src/plugin/tune.ts` line 336 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaRIXXDzrPq6sWdBdg:-NRaRIXXDzrPq6sWdBdh:bmb27ue) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/plugin/tune.ts#L336)):*
> ```XML
>     const tags = getTags(selection)
> 
>     const animationTags = tags.find((t) => t.startsWith('wiggle') || t.startsWith('fly-from-') || t.startsWith('appear') || t.startsWith('blink') || t.startsWith('draw-line'))
> ```

Одним регексом
___
*[`src/plugin/tune.ts` line 338 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaRYxnE5ibODEpxpDG:-NRaRYxnE5ibODEpxpDH:b-bjrr96) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/plugin/tune.ts#L338)):*
> ```XML
>     const animationTags = tags.find((t) => t.startsWith('wiggle') || t.startsWith('fly-from-') || t.startsWith('appear') || t.startsWith('blink') || t.startsWith('draw-line'))
>     const delay = tags.find((t) => /^d\d+/.test(t)) || tags.find((t) => /^d-\d+/.test(t))
>     const delayNumber = delay ? parseInt(delay.slice(-1)) : 0
> ```

Пожалуйста просто возьми функции getParamValue или stripSettings из task.js и допиши опциональный дефис. Не надо многократно дублировать одинаковый некрасивый код.


<!-- Sent from Reviewable.io -->

2023-04-06 12:20 UTC, Ivan-okolzin reviewed
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/32)* status: 0 of 1 approvals obtained, 1 of 17 files reviewed, 11 unresolved discussions (waiting on @ulitiy)

___
*[`src/plugin/tune.ts` line 243 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaPZti3QxQOeGW7ZjC:-NRmqci9AQlBp9WI8koM:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/plugin/tune.ts#L243)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

сделай пожалуйста просто один .filter, без переопределения.

И одним регексом. Ты мэтчишь все анимации и в начале ставишь одно отрицание.
</blockquote></details>

Done.
___
*[`src/plugin/tune.ts` line 314 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaXZVJE8_JJDN2s479:-NRbnFlrC8265DWotCZE:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/plugin/tune.ts#L314)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

page сделать вторым опциональным параметром, от обёртки избавиться
</blockquote></details>

Done.
___
*[`src/plugin/tune.ts` line 317 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaPI0c6d5MDo38K66m:-NRbnFcY8YFTYXeyOcIr:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/plugin/tune.ts#L317)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

избыточная обёртка.
</blockquote></details>

Done.
___
*[`src/plugin/tune.ts` line 336 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaRIXXDzrPq6sWdBdg:-NRbToov1w9nF_krtGAm:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/plugin/tune.ts#L336)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Одним регексом
</blockquote></details>

Done.



_Code quote:_
```XML
 const animationTags = tags.find((t) => t.startsWith('wiggle') || t.startsWith('fly-from-') || t.startsWith('appear') || t.startsWith('blink') || t.startsWith('draw-line'))
```
___
*[`src/plugin/tune.ts` line 338 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaRYxnE5ibODEpxpDG:-NRbgg_E29b6IjDZTZD5:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/plugin/tune.ts#L338)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Пожалуйста просто возьми функции getParamValue или stripSettings из task.js и допиши опциональный дефис. Не надо многократно дублировать одинаковый некрасивый код.
</blockquote></details>

Done.
___
*[`src/app/components/uiRPC.ts` line 7 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaTG3K6GvgtK5UaZaK:-NSLVjrMD3jyh0CMb_vH:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/app/components/uiRPC.ts#L7)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Интерфейс можно вынести, чтобы не дублировать. И можно ли в таком случае этот файл влить в rpc-api? Мне не нравится название этого файла, я не понимаю из него, это UI вызывает RPC или это UI RPC API.
</blockquote></details>

Done.
___
*[`src/app/models/rpc.ts` line 3 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaO4FzBMjH0hIF67Ze:-NRbtS_f-IWPGmXI3CI_:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/app/models/rpc.ts#L3)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Нужно более точное название, TuneFormStore. И файл тоже. Вроде нет необходимости привязывать этот стор именно к RPC, лучше его привязать к потребителю, т.е. к форме.
</blockquote></details>

Done.
___
*[`src/app/models/rpc.ts` line 4 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaYJZf62na16XD7RGZ:-NRbsofVBjRIzqoCSsHh:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/app/models/rpc.ts#L4)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Если все эти свойства убрать в дополнительный объект, то заменять его можно будет одной строчкой, а не каждое свойство в отдельности.

Предлагаю назвать, например formProps или formProperties, как больше нравится, главное, чтобы совпадало с методами.
</blockquote></details>

Done.
___
*[`src/app/models/rpc.ts` line 23 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaTPrREwAQgxeTAHo4:-NRbvEqb8Dd8rsNTkJAH:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/app/models/rpc.ts#L23)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

интерфейс можно вынести, чтобы не дублировать.
</blockquote></details>

Done.
___
*[`src/app/components/DisplayForm.tsx` line 32 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaOUJUEWzVqHwNFHHb:-NRbRuy2D6Egs1gowOvg:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/app/components/DisplayForm.tsx#L32)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Предлагаю переименовать в TuneForm, и файл тоже. Только аккуратно, чтобы дифф не поехал
</blockquote></details>

Done.
___
*[`src/app/components/DisplayForm.tsx` line 192 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaVT-L2RgOre9sROlT:-NSLVhNS6L8ehB9mlzpS:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/app/components/DisplayForm.tsx#L192)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Я предлагаю отказываться от отдельного локального useState и использовать valtio useSnapshot.
Зачем это дублирование стейта?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-11 03:43 UTC, ulitiy requested changes
> Reviewed 15 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/32)* status: 0 of 1 approvals obtained, 16 of 17 files reviewed, 8 unresolved discussions (waiting on @Ivan-okolzin)

___
*[`src/app/components/StepList.tsx` line 35 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NSiP6LxCSZc1jbhXxcC:-NSiP6Ly7OsrT4x9jACM:b-kalyva) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8ca5d6e09fa41828cce50eaacd9b2cc4576a792c/src/app/components/StepList.tsx#L35)):*
> ```XML
>           <ListGroup {...provided.droppableProps} ref={provided.innerRef}>
>             {steps.map((stepNode, index) => {
>               return stepNode && selectedStep ? (
> ```

Почему selectedStep необходим здесь?
___
*[`src/plugin/tune.ts` line 243 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaPZti3QxQOeGW7ZjC:-NSi1pI86ztx2ApbAerU:b-exhu0q) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/plugin/tune.ts#L243)):*
<details><summary><i>Previously, Ivan-okolzin wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Не решено
___
*[`src/plugin/tune.ts` line 338 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaRYxnE5ibODEpxpDG:-NSi2KZA2tWtQA1K1PSb:b-w5hn8q) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/plugin/tune.ts#L338)):*
<details><summary><i>Previously, Ivan-okolzin wrote…</i></summary><blockquote>

Done.
</blockquote></details>

одним регексом
___
*[`src/plugin/tune.ts` line 196 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NSi1Ig8ErM1xlEb0oCM:-NSi1Ig9AJNx2Qybkc5G:bllxu9g) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8ca5d6e09fa41828cce50eaacd9b2cc4576a792c/src/plugin/tune.ts#L196)):*
> ```XML
> ) {
>   if (!page) {
>     page = figma.currentPage
> ```

page = page || figma.currentPage
___
*[`src/plugin/tune.ts` line 267 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NSi1_mUBOdxZqEzdoTz:-NSi1_mUBOdxZqEzdoU-:b-8tpgpv) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8ca5d6e09fa41828cce50eaacd9b2cc4576a792c/src/plugin/tune.ts#L267)):*
> ```XML
> 
> setTimeout(() => {
>   updateDisplay({ displayMode: 'all', stepNumber: 1 }, figma.currentPage)
> ```

можно опустить это значение здесь и в других местах
___
*[`src/app/components/TuneForm.tsx` line 129 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NShyV6_A3v-0SKGdyOu:-NShyV6_A3v-0SKGdyOv:b-6bvqj1) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8ca5d6e09fa41828cce50eaacd9b2cc4576a792c/src/app/components/TuneForm.tsx#L129)):*
> ```XML
>   }
> 
>   // useEffect(() => {
> ```

Эти комменты зачем тут остались?
___
*[`src/app/components/TuneForm.tsx` line 144 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NShyzbCCRIzqJSHxKfF:-NShyzbCCRIzqJSHxKfG:b9l8ldt) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8ca5d6e09fa41828cce50eaacd9b2cc4576a792c/src/app/components/TuneForm.tsx#L144)):*
> ```XML
> 
> 
>   useEffect(() => {
> ```

useEffect(getSteps, [state]) не сработает вместо всего этого кода?


<!-- Sent from Reviewable.io -->

2023-04-11 03:43 UTC, ulitiy reviewed
> Reviewed 1 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/32)* status: 0 of 1 approvals obtained, all files reviewed, 8 unresolved discussions (waiting on @Ivan-okolzin)



<!-- Sent from Reviewable.io -->

2023-04-11 09:00 UTC, Ivan-okolzin commented
*[`src/app/components/StepList.tsx` line 35 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NSiP6LxCSZc1jbhXxcC:-NSjXVnsE7TKGcvyNPqj:bm2c6iu) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8ca5d6e09fa41828cce50eaacd9b2cc4576a792c/src/app/components/StepList.tsx#L35)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Почему selectedStep необходим здесь?
</blockquote></details>

Потому что есть вот эта проверка. Если быстро переключатся между страницами урока. то иногда вылетает undefined в selectedStep и stepNode и все падает.  



_Code quote:_
```XML
active={stepNode.id === selectedStep.id}
```


<!-- Sent from Reviewable.io -->

2023-04-11 10:50 UTC, Ivan-okolzin commented
*[`src/app/components/TuneForm.tsx` line 144 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NShyzbCCRIzqJSHxKfF:-NSjw5lv7nzjwgVtm1LC:b-1qhim0) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8ca5d6e09fa41828cce50eaacd9b2cc4576a792c/src/app/components/TuneForm.tsx#L144)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

useEffect(getSteps, [state]) не сработает вместо всего этого кода?
</blockquote></details>

Не сработает. 


<!-- Sent from Reviewable.io -->

2023-04-11 11:22 UTC, Ivan-okolzin reviewed
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/32)* status: 0 of 1 approvals obtained, all files reviewed, 7 unresolved discussions (waiting on @ulitiy)

___
*[`src/plugin/tune.ts` line 243 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaPZti3QxQOeGW7ZjC:-NSjoo5f0If0A8DfFnml:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/plugin/tune.ts#L243)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Не решено
</blockquote></details>

Done.
___
*[`src/plugin/tune.ts` line 338 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NRaRYxnE5ibODEpxpDG:-NSjpQhK11BbzVL97XZv:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/d7261330cf1ecbc00b60c7eb70c688cbd0d8d312/src/plugin/tune.ts#L338)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

одним регексом
</blockquote></details>

Done.
___
*[`src/plugin/tune.ts` line 196 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NSi1Ig8ErM1xlEb0oCM:-NSjhljD9guYRLEJhFEa:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8ca5d6e09fa41828cce50eaacd9b2cc4576a792c/src/plugin/tune.ts#L196)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

page = page || figma.currentPage
</blockquote></details>

Done.
___
*[`src/plugin/tune.ts` line 267 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NSi1_mUBOdxZqEzdoTz:-NSji4EI0E6F2rW_h6P9:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8ca5d6e09fa41828cce50eaacd9b2cc4576a792c/src/plugin/tune.ts#L267)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

можно опустить это значение здесь и в других местах
</blockquote></details>

Done.
___
*[`src/app/components/TuneForm.tsx` line 129 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NShyV6_A3v-0SKGdyOu:-NSjhUBKCYcr_prKqXLc:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8ca5d6e09fa41828cce50eaacd9b2cc4576a792c/src/app/components/TuneForm.tsx#L129)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Эти комменты зачем тут остались?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-12 02:56 UTC, ulitiy requested changes
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/32)* status: 0 of 1 approvals obtained, all files reviewed, 4 unresolved discussions (waiting on @Ivan-okolzin)

*[a discussion](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NSmwyJR-QZtkrh6dY6R:-NSmwyJS04cKkwhcEOvD:bjaiu8m) (no related file):*
При открытии на course easter copy, есть ошибка в консоли

tune.ts:156 Uncaught (in promise) ReferenceError: figma is not defined
    at <anonymous>:106053:24
    at Generator.next (<anonymous>)
    at <anonymous>:105904:71
    at new Promise (<anonymous>)
    at ./src/plugin/tune.ts.__awaiter (<anonymous>:105900:12)
    at updateDisplay (<anonymous>:106052:12)
    at <anonymous>:106115:5

___
___
*[`src/app/components/StepList.tsx` line 35 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NSiP6LxCSZc1jbhXxcC:-NSmlQED1ppniIeNE2iF:bvonpyk) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8ca5d6e09fa41828cce50eaacd9b2cc4576a792c/src/app/components/StepList.tsx#L35)):*
<details><summary><i>Previously, Ivan-okolzin wrote…</i></summary><blockquote>

Потому что есть вот эта проверка. Если быстро переключатся между страницами урока. то иногда вылетает undefined в selectedStep и stepNode и все падает.  
</blockquote></details>

так может быть нужно в этом месте дописать selectedStep?.id, а не убивать весь список целиком?
___
*[`src/plugin/tune.ts` line 276 at r3](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NSmj5Nm5PqysgAjTvrN:-NSmj5Nm5PqysgAjTvrO:b-t0zam2) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/cecf93ef6e6451714537a7ff4eb408122daeadfe/src/plugin/tune.ts#L276)):*
> ```XML
>   if (figma.currentPage.selection) {
>     let selectionTags = getTags(figma.currentPage.selection[0]).filter((t) => {
>       return !/^(wiggle|fly-from-|appear|blink|draw-line)|([dr]-\d+)|([dr]\d+)$/g.test(
> ```

`/^(wiggle|fly-from-|appear$|blink$|draw-line|[dr]-?\d+$)/g`
___
*[`src/app/components/TuneForm.tsx` line 144 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/32#-NShyzbCCRIzqJSHxKfF:-NSmtyY19F5w_AJDS4fr:b-nl8d8w) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8ca5d6e09fa41828cce50eaacd9b2cc4576a792c/src/app/components/TuneForm.tsx#L144)):*
<details><summary><i>Previously, Ivan-okolzin wrote…</i></summary><blockquote>

Не сработает. 
</blockquote></details>

```
  useEffect(() => {
    getSteps()
  }, [state])
```
почему у меня работает?


<!-- Sent from Reviewable.io -->

2023-04-12 08:12 UTC, Ivan-okolzin commented
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

При открытии на course easter copy, есть ошибка в консоли

tune.ts:156 Uncaught (in promise) ReferenceError: figma is not defined
    at <anonymous>:106053:24
    at Generator.next (<anonymous>)
    at <anonymous>:105904:71
    at new Promise (<anonymous>)
    at ./src/plugin/tune.ts.__awaiter (<anonymous>:105900:12)
    at updateDisplay (<anonymous>:106052:12)
    at <anonymous>:106115:5
</blockquote></details>

Видел эту ошибку. Возникает из за timeout'a, который вызывает updateDisplay при открытии плагина. Я убрал его и потестил(Ничего не изменилось, учитывая, что updateDisplay не выполнялся и до этого из за ошибки0




<!-- Sent from Reviewable.io -->

2023-04-12 14:51 UTC, ulitiy approved these changes
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/32)* status: :shipit: complete! 1 of 1 approvals obtained, all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-16 17:15 UTC, ulitiy approved these changes
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/32)* status: :shipit: complete! 1 of 1 approvals obtained, all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-19 19:34 UTC, ulitiy approved these changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/32)* status: :shipit: complete! 1 of 1 approvals obtained, all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-04-19 19:34 UTC, merged