Add step color indication
ulitiy/artworkout-figma pull request #4
Opened 2022-11-22 19:27 UTC by ant4x

2022-11-22 20:31 UTC, ulitiy requested changes

2022-11-22 20:31 UTC, ulitiy commented on src/app/components/StepList.tsx
> +  stepNodes: any[]
Объяви нормальный тип пожалуйста, и типизируй возврат из getStepNodes под него тоже.
Раз это по факту не ноды, а некая репрезентация, то их можно переименовать типа steps/selectedStep.

2022-11-22 20:31 UTC, ulitiy commented on src/plugin/tune-rpc.ts
> +    // TODO: check other cases
Ну а зачем оставлять наполовину доделанную задачу, надо доделать, у нас много где используются другие виды "листьев".

Ты даже тайпскрипту тут не угождаешь, раз у тебя SceneNode остается тип, смысл в свитче?
Просто проверь наличие fills/strokes и вынимай оттуда, если они есть. Код получится короче и понятней. Логи эти тоже убирай. Let it fail.

2022-11-22 20:31 UTC, ulitiy commented on src/plugin/tune-rpc.ts
> +    }
if/else, лог убирай.

2022-11-23 16:58 UTC, ant4x commented on src/app/components/StepList.tsx
> +  stepNodes: any[]
Done

2022-11-23 16:58 UTC, ant4x commented on src/plugin/tune-rpc.ts
> +    // TODO: check other cases
Done

2022-11-23 16:59 UTC, ant4x commented on src/plugin/tune-rpc.ts
> +    }
Done

2022-11-23 23:18 UTC, ulitiy approved these changes

2022-11-23 23:19 UTC, merged