add container to icons
ulitiy/artworkout-figma pull request #5
Opened 2022-11-25 20:08 UTC by ant4x

2022-11-26 16:38 UTC, ulitiy requested changes

2022-11-26 16:38 UTC, ulitiy commented on src/app/components/StepList.tsx
> +                        {!stepNode.name.includes('result') ? (
getTags includes s-multistep-result

2022-11-26 16:38 UTC, ulitiy commented on src/plugin/tune-rpc.ts
> +    strokesColor: displayColor(strokes),
eslint указывает на ошибку здесь

2022-11-26 17:44 UTC, ant4x commented on src/app/components/StepList.tsx
> +                        {!stepNode.name.includes('result') ? (
Done

2022-11-26 17:44 UTC, ant4x commented on src/plugin/tune-rpc.ts
> +    strokesColor: displayColor(strokes),
Fixed

2022-11-26 23:16 UTC, ulitiy requested changes

2022-11-26 23:16 UTC, ulitiy commented on src/plugin/tune-rpc.ts
> +  a: number
https://www.figma.com/plugin-docs/api/RGB вот готовый интерфейс же

2022-11-26 23:16 UTC, ulitiy commented on src/plugin/tune-rpc.ts
> +  const { r, g, b, a } = color
https://mariusschulz.com/blog/typing-destructured-object-parameters-in-typescript

2022-11-26 23:16 UTC, ulitiy commented on src/plugin/tune-rpc.ts
>    let fills: { r: number; g: number; b: number; a: number } = defaultColor
тоже

2022-11-28 16:33 UTC, ant4x commented on src/plugin/tune-rpc.ts
>    let fills: { r: number; g: number; b: number; a: number } = defaultColor
Fixed

2022-11-28 17:10 UTC, ant4x commented on src/plugin/tune-rpc.ts
> +  const { r, g, b, a } = color
Прочитал, отредактировал код

2022-11-28 18:34 UTC, ulitiy approved these changes

2022-11-28 18:41 UTC, merged