Implement "Create Lesson" feature
ulitiy/artworkout-figma pull request #7
Opened 2022-12-02 16:23 UTC by ant4x

2022-12-02 23:00 UTC, ulitiy requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/7)* status: all files reviewed, 11 unresolved discussions (waiting on @ant4x)

___
*[`src/app/components/App.tsx` line 44 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIJsha887-V6OARzVvA:-NIJsha887-V6OARzVvB:b-n7y4f3) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/app/components/App.tsx#L44)):*
> ```XML
>     <Tabs defaultActiveKey='tune' className='m-1'>
>       <Tab eventKey='create' title='Create' className='m-2 text-center'>
>         <Button onClick={() => emit('createLesson')} className='m-2'>
> ```

Переделай на использование RPC
___
*[`src/app/components/App.tsx` line 48 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIJspvh06bW0ceymM_g:-NIJspvh06bW0ceymM_h:b-26xvd8) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/app/components/App.tsx#L48)):*
> ```XML
>         </Button>
>         {/* <Button>Set animations (CONFIRM)</Button> */}
>         <Button onClick={() => emit('separateStep')}>Separate step</Button>
> ```

Здесь тоже RPC заодно сделай
___
*[`src/plugin/create.ts` line 23 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIJwVHJ4Vpyr5_8oiKJ:-NIJwVHJ4Vpyr5_8oiKK:bxcdwzn) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/plugin/create.ts#L23)):*
> ```XML
> }
> 
> function displayImage(node: PageNode, el: FrameNode | RectangleNode) {
> ```

Я не понимаю, что здесь происходит... Почему эта функция называется displayImage?
Что она делает? По коду очевидно, что она не делает того, что написано в названии.

P.s. понял. Не надо так)
удаляй эту функцию
___
*[`src/plugin/create.ts` line 59 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIJy2at-xCUpMS7ibP2:-NIJy2au7svo3mOVXpW4:b-mbiupu) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/plugin/create.ts#L59)):*
> ```XML
> 
> function createLesson(node: PageNode) {
>   figma.currentPage.name = 'image'
> ```

Зачем? Убирай.
___
*[`src/plugin/create.ts` line 60 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIK1aMN1Ue7gNOvyJzX:-NIK1aMN1Ue7gNOvyJzY:b-k2esjo) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/plugin/create.ts#L60)):*
> ```XML
> function createLesson(node: PageNode) {
>   figma.currentPage.name = 'image'
>   if (node.children.length !== 1) {
> ```

Это разумное ограничение
___
*[`src/plugin/create.ts` line 67 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIK0BGB5w3Io1JL1Obh:-NIK0BGC5ZkhrJXWjwl2:b-c83jhr) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/plugin/create.ts#L67)):*
> ```XML
>   const isImage =
>     originalImage.type === 'RECTANGLE' &&
>     originalImage.fills[0].type === 'IMAGE'
> ```

Нееее, мы вставляем ВЕКТОРНУЮ картинку, SVG файл.

Как мы будем растр на куски-то бить?

Поэтому кнопка не работает так, как я ожидал. Ну тут просто ты не понял требования и не уточнил.

Но, на самом деле, без разницы что там конкретно. Ты просто должен целиком любой существующий элемент вставить и всё, какая разница, вектор это или растр или просто кружок юзер нарисовал прямо в фигме.
___
*[`src/plugin/create.ts` line 88 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIK2Gx71g-ngHhI8Lc8:-NIK2Gx71g-ngHhI8Lc9:b-939h9l) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/plugin/create.ts#L88)):*
> ```XML
> 
>     // Create step
>     const stepRectangle = figma.createRectangle()
> ```

Это не rectangle, это frame, принципиальная разница, внимательнее.
___
*[`src/plugin/create.ts` line 90 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIK2GCK2IZU0BFBrmhf:-NIK2GCK2IZU0BFBrmhg:bo297so) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/plugin/create.ts#L90)):*
> ```XML
>     const stepRectangle = figma.createRectangle()
>     stepRectangle.name = 'image'
>     displayImage(node, stepRectangle)
> ```

Не надо так. node.clone же есть, зачем тебе лезть внутрь и ручками воспроизводить? Используй поиск по коду ".clone"
___
*[`src/plugin/create.ts` line 95 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIJwGJWDb75xU2uinTY:-NIJwGJXDCutZiTr2VFf:b-rq3wa3) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/plugin/create.ts#L95)):*
> ```XML
>       figma.currentPage.children[0].height
>     )
>     const inputStep = figma.group([stepRectangle], lesson)
> ```

stepInput. Инпут шага, а не шаг инпута.
___
*[`src/plugin/create.ts` line 99 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIK1l3U2tzzM9SPFvKE:-NIK1l3U2tzzM9SPFvKF:b-9dvj0f) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/plugin/create.ts#L99)):*
> ```XML
>     const firstStep = figma.group([inputStep], lesson)
>     formatNode(firstStep, {
>       name: 'step s-multistep-image',
> ```

Не выдумывай свои теги, они не будут работать, я просил просто скопировать существующие. `step s-multistep-brush`
___
*[`src/plugin/create.ts` line 107 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIK26qD-Owv2fBRb3uq:-NIK26qD-Owv2fBRb3ur:b-yo1kld) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/plugin/create.ts#L107)):*
> ```XML
> 
>     // Create thumbnail
>     const thumbnailRectangle = figma.createRectangle()
> ```

Это не rectangle, это frame
___
*[`src/plugin/create.ts` line 113 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIK2Zz09roWkAjSJlHw:-NIK2Zz09roWkAjSJlHx:b-v5u458) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/plugin/create.ts#L113)):*
> ```XML
>     formatNode(thumbnailGroup, {
>       name: 'thumbnail group',
>       x: 49,
> ```

откуда эти конкретные цифры? Не надо считать, что юзер будет вставлять только картинки определенного размера. Нужно отмасштабировать контент по принципу fit в определенные рамки (отступ 35 пикселей от каждого края), без всякого кропа и непропорционального ресайза.


<!-- Sent from Reviewable.io -->

2022-12-03 00:22 UTC, ulitiy requested changes
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/7)* status: all files reviewed, 11 unresolved discussions (waiting on @ant4x)

___
*[`src/plugin/create.ts` line 88 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIK2Gx71g-ngHhI8Lc8:-NIKLlZg9ZjLcpCTF9m8:bz8fc0u) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/plugin/create.ts#L88)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Это не rectangle, это frame, принципиальная разница, внимательнее.
</blockquote></details>

А, понял. Ну не надо. Просто клонируй всё, что дали.
___
*[`src/plugin/create.ts` line 107 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIK26qD-Owv2fBRb3uq:-NIKLvFH0KiBKpvownHL:bpwiive) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/plugin/create.ts#L107)):*
> А, понял. Ну не надо. Просто клонируй всё, что дали.


<!-- Sent from Reviewable.io -->

2022-12-04 22:34 UTC, ant4x reviewed
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/7)* status: 0 of 6 files reviewed, 11 unresolved discussions (waiting on @ulitiy)

___
*[`src/app/components/App.tsx` line 44 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIJsha887-V6OARzVvA:-NIUBni9EOMP3IBv4meN:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/app/components/App.tsx#L44)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Переделай на использование RPC
</blockquote></details>

Done.
___
*[`src/app/components/App.tsx` line 48 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIJspvh06bW0ceymM_g:-NIUBomw8uy_Ixemz0Ca:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/app/components/App.tsx#L48)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Здесь тоже RPC заодно сделай
</blockquote></details>

Done.
___
*[`src/plugin/create.ts` line 23 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIJwVHJ4Vpyr5_8oiKJ:-NIUBqM004PNZeWLzYgy:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/plugin/create.ts#L23)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Я не понимаю, что здесь происходит... Почему эта функция называется displayImage?
Что она делает? По коду очевидно, что она не делает того, что написано в названии.

P.s. понял. Не надо так)
удаляй эту функцию
</blockquote></details>

Done.
___
*[`src/plugin/create.ts` line 59 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIJy2at-xCUpMS7ibP2:-NIUBrIv4va6TElve925:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/plugin/create.ts#L59)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Зачем? Убирай.
</blockquote></details>

Done.
___
*[`src/plugin/create.ts` line 67 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIK0BGB5w3Io1JL1Obh:-NIUBztT7sR7Z9PimPm8:b-irrvrh) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/plugin/create.ts#L67)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Нееее, мы вставляем ВЕКТОРНУЮ картинку, SVG файл.

Как мы будем растр на куски-то бить?

Поэтому кнопка не работает так, как я ожидал. Ну тут просто ты не понял требования и не уточнил.

Но, на самом деле, без разницы что там конкретно. Ты просто должен целиком любой существующий элемент вставить и всё, какая разница, вектор это или растр или просто кружок юзер нарисовал прямо в фигме.
</blockquote></details>

Я делал первую (черновую) версию фичи, чтобы получить фидбэк и доделать все детали. 
Поправил замечания.
___
*[`src/plugin/create.ts` line 88 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIK2Gx71g-ngHhI8Lc8:-NIUCbmWEhVQk5g_XxcK:b4x4mah) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/plugin/create.ts#L88)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

А, понял. Ну не надо. Просто клонируй всё, что дали.
</blockquote></details>

Ок, сделал
___
*[`src/plugin/create.ts` line 90 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIK2GCK2IZU0BFBrmhf:-NIUCgyB8MOmLlbHw5fN:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/plugin/create.ts#L90)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Не надо так. node.clone же есть, зачем тебе лезть внутрь и ручками воспроизводить? Используй поиск по коду ".clone"
</blockquote></details>

Done.
___
*[`src/plugin/create.ts` line 95 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIJwGJWDb75xU2uinTY:-NIUCiWK05gsH3TTTiO5:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/plugin/create.ts#L95)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

stepInput. Инпут шага, а не шаг инпута.
</blockquote></details>

Done.
___
*[`src/plugin/create.ts` line 99 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIK1l3U2tzzM9SPFvKE:-NIUCjf6DGLVVBiXh3RP:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/plugin/create.ts#L99)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Не выдумывай свои теги, они не будут работать, я просил просто скопировать существующие. `step s-multistep-brush`
</blockquote></details>

Done.
___
*[`src/plugin/create.ts` line 107 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIK26qD-Owv2fBRb3uq:-NIUCm268pyOFHJyOEPY:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/plugin/create.ts#L107)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

> А, понял. Ну не надо. Просто клонируй всё, что дали.
</blockquote></details>

Done.
___
*[`src/plugin/create.ts` line 113 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIK2Zz09roWkAjSJlHw:-NIUCstGC-D2cwX_sg99:bxdnu3d) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/plugin/create.ts#L113)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

откуда эти конкретные цифры? Не надо считать, что юзер будет вставлять только картинки определенного размера. Нужно отмасштабировать контент по принципу fit в определенные рамки (отступ 35 пикселей от каждого края), без всякого кропа и непропорционального ресайза.
</blockquote></details>

Это был черновой вариант, переделал. Конкретные цифры на Frame нодах lesson и thumbnail скопировал как были в demo уроке. Если надо вычислять - напиши как они вычисляются сейчас?


<!-- Sent from Reviewable.io -->

2022-12-05 00:37 UTC, ulitiy approved these changes
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ant4x)

___
*[`src/plugin/create.ts` line 67 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/7#-NIK0BGB5w3Io1JL1Obh:-NIUdbNX2FGw7e1IaGGf:b-oiq8zf) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/ae4e58fae7a90c398db7b85484f08e3b173b9797/src/plugin/create.ts#L67)):*
<details><summary><i>Previously, ant4x (Anthony Fox) wrote…</i></summary><blockquote>

Я делал первую (черновую) версию фичи, чтобы получить фидбэк и доделать все детали. 
Поправил замечания.
</blockquote></details>

Ага, хорошо.


<!-- Sent from Reviewable.io -->

2022-12-05 00:37 UTC, merged